# CAREFUL: yaml is super sensitive to spaces - don't use tabs

# Parameters defining signal maps
simparams:
    nrealiz: 1
    probes: ['deltag', 'cmbkappa', 'gamma']
    spins: [0, 0, 2]
    path2cls: ['../../data/cl_gg.txt', '../../data/cl_gk.txt', '../../data/cl_gs.txt', '../../data/cl_kk.txt', '../../data/cl_ks.txt', '../../data/cl_ss.txt']
    l0_bins: [213.0373, 291.0176, 397.5417, 543.0580, 741.8391, 1013.3821, 1384.3207, 1891.0378]
    lf_bins: [291.0176, 397.5417, 543.0580, 741.8391, 1013.3821, 1384.3207, 1891.0378, 2583.2338]
    nside: 1024
    pixwindow: 1
    nell_theor: 3501

# Parameters defining noise maps
# If noiseparams: null, then noise-free mocks will be generated
noiseparams: 
    probes: ['deltag', 'cmbkappa', 'gamma']
    noisemodel: theory
    path2noisecls: ['../../data/ncl_gg.txt', '../../data/ncl_kk.txt', '../../data/ncl_ss.txt']

path2mask: '../../data/mask.fits'

# Parameters defining this specific run
mode: curved
path2outputdir: '../../data/'
